# Generated by Django 5.2.7 on 2025-10-26 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PcapFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=1024, unique=True)),
                ("file_timestamp", models.DateTimeField()),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["path"],
            },
        ),
        migrations.CreateModel(
            name="PacketIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("packet_id", models.BigIntegerField()),
                ("packet_timestamp", models.DateTimeField()),
                ("offset", models.BigIntegerField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pcap_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packet_indices",
                        to="pcapindex.pcapfile",
                    ),
                ),
            ],
            options={
                "ordering": ["pcap_file", "packet_id"],
                "indexes": [
                    models.Index(
                        fields=["pcap_file", "packet_id"],
                        name="pcapindex_p_pcap_fi_727636_idx",
                    ),
                    models.Index(
                        fields=["pcap_file", "packet_timestamp"],
                        name="pcapindex_p_pcap_fi_95b554_idx",
                    ),
                ],
                "unique_together": {("pcap_file", "packet_id")},
            },
        ),
        migrations.CreateModel(
            name="PacketCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cache_key", models.CharField(max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pcap_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caches",
                        to="pcapindex.pcapfile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["pcap_file", "cache_key"],
                        name="pcapindex_p_pcap_fi_72dd38_idx",
                    ),
                    models.Index(
                        fields=["last_updated"], name="pcapindex_p_last_up_e30246_idx"
                    ),
                ],
                "unique_together": {("pcap_file", "cache_key")},
            },
        ),
    ]
